camunda.bpm.admin-user:
  id: demo
  password: demo
spring:
  kafka:
    bootstrap-servers: 172.25.43.101:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: camunda
  datasource:
    url: jdbc:h2:file:./camunda-h2-database
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8080